[build]
install = "npm ci && npm install @rollup/rollup-linux-x64-gnu --save-optional"
build = "npm run build --workspace=backend && npm run build --workspace=frontend"

[start]
cmd = "npm run start --workspace=backend"

[environments]
NODE_ENV = "production"
